### ISSUE TITLE
Add a Licence

### ISSUE THREAD

**Issue by brian-codes** [duncanheron/dropPin#10]
Hey, would love to use this for a little feature I'm working on. Is it possible to add a licence? happy to put in a PR to add one if it's ok.

**Comment by duncanheron** [comment]
@brian-codes go for it. This has been sitting unused for quite some time, so glad its still being used at all :)
It could probably do with some TLC.

**Comment by brian-codes** [comment]
Thank you, perfect!

**Comment by duncanheron** [comment]
Good luck - be good to see what comes of it.
