### ISSUE TITLE
pinClass is not working

### ISSUE THREAD

**Issue by nicolaeum** [duncanheron/dropPin#5]
Hi! im using two different instances (#map & #map2) in the same page, everything goes ok but when Im pointing / clicking on #map1, the pin belonging to #map2 get lost. I've tried to use the pinClass option this change nothing :(

Both pins have the same class and thats a problem.

Many thanks and nice work

**Comment by duncanheron** [comment]
Hey - have updated the single pin drop to use the custom pinClass.

Let me know if that solves your issue
