### ISSUE TITLE
Is there complete code for multi pen entry and saving to database with a name/title for each pin dropped

### ISSUE THREAD

**Issue by donlaur** [duncanheron/dropPin#6]
I don't see how to add the data to a mysql database with jquery after the pins are added.  I especially want to also add a title, say "My House" that can be edited after the pin is dropped.  Thanks.

**Comment by coffeeshopcoder** [comment]
Hidden form fields can be updated with coordinates if you set their ids when initializing. You can watch for changes in said form fields and send them to your back end code via ajax.

You'll have to write your own code for sending ajax calls to your back end as well as the back end code for inserting into the database itself.

Simply put, the plugin doesn't provide the complete feature set for saving pins to the database, but there is a way if you're willing to write parts of the code to handle ajax calls and db inserts.

**Comment by duncanheron** [comment]
@donlaur as @coffeeshopcoder (thanks for your reply) mentioned this is just the javascript frontend implementation. You should save to the database either using ajax or a simple form submit and save with PHP (or whatever server side language you are using). In it's simplest form you could just serialise or json_encode the data to one field in the db to save time, then use the javascript method provided to bring it back into the map and unencode it.
